### ISSUE TITLE
Add current round to coloured grid on division page

### ISSUE THREAD

**Issue by jakeprinscoding** [TMLeague/TMLeague.github.io#592]
Take this page here, for example:
https://tmleague.github.io/league/loiaf/season/s23/division/d1

I can click the little down arrow to expand a full grid of all 10 players and all 10 games. This is great! The only thing that would be nice, though, would be if we could add a row at the bottom for the current round of each game. Towards the end of the season, in particular, it would be nice to know which games are ongoing and which games are finished.

For LoIaF, since not all games finish, it might also be nice (at the end of the season) to be able to distinguish between games which finished, games which were simulated, and games which didn't finish. Something like:
- 2: indicates an active game (in round 2)
- 9: indicates an active game (in round 9)
- F7: indicates a game which finished in round 7
- U9: indicates an unfinished game for which the results from the end of round 9 were taken
- S10: indicates a game which was simulated and ended in round 10

Something like that? If that's too complicated, even just having "9" or "F" would be helpful too.

**Comment by Imrihil** [comment]
Isn't the current league progress in the league home page enough?
But in general it's doable and I can implement it in the future. :)

**Comment by jakeprinscoding** [comment]
Yeah, it's on the league page and helpful there. But on the division page, there is no indication anywhere what round any game is in (or if a game is finished) - to find that info you either have to have both pages open in different windows or switch back and forth.

This is a pretty small thing, you're right ;) but would definitely be nice to have!

**Comment by Imrihil** [comment]
Done: https://github.com/TMLeague/TMLeague.github.io/pull/705
