### ISSUE TITLE
Division results show promoted players

### ISSUE THREAD

**Issue by Imrihil** [TMLeague/TMLeague.github.io#71]
There should be a config in the League about number of players promoted and relegated from specific divisions.

There should be also an option to override some settings for specific seasons and divisions.

**Comment by jakeprinscoding** [comment]
This was going to be one of my requests! Could also be cool if the winner of D1 got a special color? So promoted players are green, relegated players are red, and champion is gold, or something?

**Comment by Imrihil** [comment]
That is exactly my intention. :)

**Comment by jakeprinscoding** [comment]
Love it!
